controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# -------------------------------- #
#  Rutas para el manejo de usuarios
# -------------------------------- #

#Registrar usuario
register:
    path: /register
    controller: App\Controller\RegisterController::index

logout:
    path: /logout
    controller: App\Controller\LogoutController::logout

# -------------------------------- #
#         Rutas error              #
# -------------------------------- #

error:
    path: /error/{code}
    controller: App\Controller\ErrorController::main


# -------------------------------- #
#         Rutas aplicación         #
# -------------------------------- #

#Página principal
home:
    path: /
    controller: App\Controller\HomeController::home

panel_home:
    path: /panel-home
    controller: App\Controller\PanelController::home

crear-cuentas-bancarias:
    path: /crear-cuentas-bancarias
    controller: App\Controller\PanelController::crear_cuentas_bancarias

detalles-cuenta-bancaria:
    path: /detalles-cuenta-bancaria/{iban}
    controller: App\Controller\PanelController::detalles_cuenta_bancaria

add-movimientos:
    path: /add-movimientos/{iban}
    controller: App\Controller\PanelController::add_movimientos

editar-cuenta:
    path: /editar-cuenta/{iban}
    controller: App\Controller\PanelController::editar_cuenta

eliminar-cuenta:
    path: /eliminar-cuenta/{iban}
    controller: App\Controller\PanelController::eliminar_cuenta

confirmar-eliminar-cuenta:
    path: /confirmar-eliminar-cuenta/{iban}
    controller: App\Controller\PanelController::confirmar_eliminar_cuenta

bulk-movimientos-bancarios:
    path: /bulk-movimientos-bancarios/{iban}
    controller: App\Controller\PanelController::bulk_movimientos_bancarios

categorizar-movimientos-bancarios:
    path: /categorizar-movimientos-bancarios/{iban}
    controller: App\Controller\PanelController::categorizar_movimientos_bancarios

inversiones:
    path: /inversiones
    controller: App\Controller\PanelController::inversiones


# -------------------------------- #
#         Rutas JavaScript         #
# -------------------------------- #

editar-movimiento:
    path: /panel/movimiento/editar/{id}
    controller: App\Controller\PanelController::editarMovimiento
    methods: [POST]